config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :chatrooms do
  	resource :chatroom_users
  	resources :messages
  end

  root 'chatrooms#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
	has_many :chatroom_users
	has_many :users, through: :chatroom_users

	has_many :messages, dependent: :destroy
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  mount_uploader :avatar, FileUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar, :avatar_cache, :remove_avatar])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar, :avatar_cache, :remove_avatar])
  end
end

app/controllers/chatroom_users_controller.rb
class ChatroomUsersController < ApplicationController
	before_action :authenticate_user!
	before_action :set_chatroom
	def create
		@chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
		redirect_to @chatroom
	end
	def destroy
		@chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).destroy_all
		redirect_to chatrooms_path
	end

	private

	def set_chatroom
		@chatroom = Chatroom.find(params[:chatroom_id])
	end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.all
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
    unless @chatroom.users.include?(current_user)
      redirect_to root_path
    end
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to root_path, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_chatroom

	def create
		message = @chatroom.messages.new(message_params)
		message.user = current_user
		message.save
		MessageRelayJob.perform_later(message)
	end
	private

	def message_params
		params.require(:message).permit(:body)
	end
	def set_chatroom
		@chatroom = Chatroom.find(params[:chatroom_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_form.html.erb
<%= form_for(chatroom) do |f| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
      <% chatroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chatroom List</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= chatroom.name %></td>
        <td><%= link_to 'Edit', edit_chatroom_path(chatroom) %></td>
        <td><%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Join', chatroom_chatroom_users_path(chatroom), method: :post %></td>
        <td><%= link_to 'Leave', chatroom_chatroom_users_path(chatroom), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chatroom', new_chatroom_path %>

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<div class="panel-heading panel-info panel">
    <b>RECENT CHAT HISTORY</b>
</div>
<div style="margin: 20px 0">
	<p><strong>Name:</strong>
	  <%= @chatroom.name %></p>


<ul class="media-list">

	<div class="scrollable" style=" max-height: 350px; overflow: auto;" id="message_dialog">
<<<<<<< HEAD
		<% @chatroom.messages.includes(:user).limit(50).each do |message| %>
			<%= render message %>
		<% end %>
		<div data-behavior='messages' data-chatroom-id='<%= @chatroom.id %>' style="padding: 10px;" >
			
<li class="media">

    <div class="media-body">

        <% if @chatroom.messages.any? and params[:message] %>
            <div class="media">
             <% if @chatroom.messages.last.user.avatar.url.present? %>
                <a class="pull-left" href="#">
                    <img class="media-object img-circle " src= <%= @chatroom.messages.last.user.avatar.url(:thumb) %> style="width: 64px; height: 64px;" />
                </a>
            <% else %>
                <a class="pull-left" href="#">
                    <img class="media-object img-circle " src= "http://res.cloudinary.com/dfg9corup/image/upload/c_scale,h_64,w_64/v1492883786/anonymous_tswtq8.png" style="width: 64px; height: 64px;" />
                </a>
            <% end %>
            <div class="media-body" >
                <%= @chatroom.messages.last.body %>
                <br />
               <small class="text-muted" ><%= @chatroom.messages.last.user.username %> |  <%= @chatroom.messages.last.created_at.to_formatted_s(:short) %></small>
                <hr />
            </div>
        </div>
        <% end %>

    </div>

</li>



=======
		<div data-behavior='messages' data-chatroom-id='<%= @chatroom.id %>' style="padding: 10px;" >
			<% @chatroom.messages.limit(100).each do |message| %>
					<%= render message %>
			<% end %>
>>>>>>> 6285d24... add avatar
		</div>
	</div>

</ul>


    <div class="panel-footer">
        <div class="input-group col-md-12 col-sm-12 col-xs-12">
        <%= form_for [@chatroom, Message.new], remote: true do |f| %>
			<%= f.text_area :body, rows: 2, class: "form-control", autofocus: true, placeholder: "Your messages here..." %>
		<% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="font-family:Verdana">
    <%= render 'shared/header' %>
    	<div class="container-fluid" style="margin: 50px 0;">
    		<div class="row">

            <div class="col-md-4">
                <% if user_signed_in? %>
                  <div class="panel panel-primary">
                    <div class="panel-heading">
<<<<<<< HEAD
                       JOINED CHAT ROOMS
=======
                       CHAT ROOMS
>>>>>>> 6285d24... add avatar
                    </div>
                    <div class="panel-body">
                        <ul class="media-list">                            
                          <% current_user.chatrooms.each do |chatroom| %>
                              <li class="media">

                                  <div class="media-body">

                                      <div class="media">
                                          <div class="media-body" >
                                              <h5><%= link_to chatroom.name, chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} %></h5>
                                          </div>
                                      </div>

                                  </div>
                              </li>
                          <% end %>
                        </ul>
                    </div>
                </div>
              <% end %>
            </div>

            <div class="col-md-8">
                <div class="panel panel-info">
                    <div class="panel-body">
                      <%= yield %>
                    </div>
                </div>
            </div>


        </div>
    	</div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/messages/_message.html.erb
<li class="media">

    <div class="media-body">

        <div class="media">
             <% if message.user.avatar.url.present? %>
                <a class="pull-left" href="#">
                    <img class="media-object img-circle " src= <%= message.user.avatar.url(:thumb) %> style="width: 64px; height: 64px;" />
                </a>
            <% else %>
                <a class="pull-left" href="#">
                    <img class="media-object img-circle " src= "http://res.cloudinary.com/dfg9corup/image/upload/c_scale,h_64,w_64/v1492883786/anonymous_tswtq8.png" style="width: 64px; height: 64px;" />
                </a>
            <% end %>
            <div class="media-body" >
            	<%= message.body %>
                <br />
<<<<<<< HEAD
               <small class="text-muted" ><%= message.user.username %> |  <%= message.created_at.to_formatted_s(:short) %></small>
=======
               <small class="text-muted"><%= message.user.username %> |  <%= message.created_at.to_formatted_s(:short) %></small>
>>>>>>> 6285d24... add avatar
                <hr />
            </div>
        </div>

    </div>

</li>

app/views/messages/create.js.erb
$("#new_message")[0].reset()

app/views/shared/_footer.html.erb
<footer class="navbar-fixed-bottom">
	<div class="panel panel-default">
	<div class="panel-footer text-center">
		Copyrights 2017, All rights reserved
	</div>
</div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<div class="navbar-brand" style="font-weight: bold;"><%= link_to 'CHAT APP',root_path %></div>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav">
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li><%= link_to 'Sign out',destroy_user_session_path, method: :delete %></li>
					<li><%= link_to 'Settings',edit_user_registration_path %></li>
				<% else %>
					<li><%= link_to 'Sign in',new_user_session_path %></li>
					<li><%= link_to 'Sign up',new_user_registration_path %></li>
				<% end %>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div>
</nav>